support kube 1.16 API
ibm-cloud-architecture/refarch-cloudnative-micro-catalog pull request #35
Opened 2019-09-30 19:40 UTC by dshimo

Catalog changes for ﻿https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/issues/210

2019-09-30 19:44 UTC, evie-lau approved these changes

2019-10-01 21:09 UTC, jjvilleg approved these changes

2019-10-02 15:26 UTC, evie-lau requested changes
`catalog.yaml` and `c_replication_controller.yaml` need `spec.selector.matchLabels`, and repackage the helm charts for both.

2019-10-03 19:32 UTC, evie-lau approved these changes

2019-10-03 19:35 UTC, merged